### ISSUE TITLE
OneClickApps: Using " in variable values breaks deployment

### ISSUE THREAD

**Issue by jfowl** [caprover/caprover-frontend#104]
Upon trying to write a OneClickApp for https://conduit.rs I ran into the following error:

![image](https://user-images.githubusercontent.com/15788906/184732566-c033074e-7639-406c-abae-14204c7931d8.png)

The variable

```yaml
 - id: '$$cap_conduit_trusted_servers'
   label: Trusted servers
   defaultValue: '["matrix.org"]'
   description: "List of servers trusted to send other server's public keys."
```
gets rendered into

```json
{
    "id": "["matrix.org"]",
   "label": "Trusted servers",
   "defaultValue": "[\"matrix.org\"]",
   "description": "List of servers trusted to send other server's public keys."
},
```

by

https://github.com/caprover/caprover-frontend/blob/60f9a44f9ebfb0a07f587bec2c64c31be1983bd3/src/containers/apps/oneclick/OneClickAppDeployManager.ts#L41-L70

Suggested fix: Maybe JSON-Escape the values before replacing text with them?
